[package]
name = "lazy-seq"
version = "0.1.0"
edition = "2021"
description = "A crate for constructing lazily evaluated sequences."
license = "MIT OR Apache-2.0"
authors = ["Aaron Manning"]
repository = "https://github.com/aaron-jack-manning/lazy-seq"

[dependencies]
